export const PranayamaCourse = {
    GET_PRANAYAMA_COURSE_DATA: 'GET_PRANAYAMA_COURSE_DATA',
    ON_PRANAYAMA_COURSE_DATA_SUCCESS: 'ON_PRANAYAMA_COURSE_DATA_SUCCESS',
    ON_PRANAYAMA_COURSE_DATA_FAIL: 'ON_PRANAYAMA_COURSE_DATA_FAIL',
};

export const Exercise = {
    GET_EXERCISE_DATA: 'GET_EXERCISE_DATA',
    ON_EXERCISE_DATA_SUCCESS: 'ON_EXERCISE_DATA_SUCCESS',
    ON_EXERCISE_DATA_FAIL: 'ON_EXERCISE_DATA_FAIL',
};


export const SignUp = {
    SET_SIGNUP_DATA: 'SET_SIGNUP_DATA',
    ON_SIGNUP_DATA_SUCCESS: 'ON_SIGNUP_DATA_SUCCESS',
    ON_SIGNUP_DATA_FAIL: 'ON_SIGNUP_DATA_FAIL',
};

export const Pranayama = {
    GET_PRANAYAMA_DATA: 'GET_PRANAYAMA_DATA',
    ON_PRANAYAMA_DATA_SUCCESS: 'ON_PRANAYAMA_DATA_SUCCESS',
    ON_PRANAYAMA_DATA_FAIL: 'ON_PRANAYAMA_DATA_FAIL',
};